name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]
jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: 'mvn -> package'
        run: 'mvn package'
    
      - name: 'mvn -> deploy'
        run: 'mvn appengine:deploy'
